# Steps represent a sequence of tasks that will be executed as part of the job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        id: repo
        uses: actions/checkout@v3

      - name: Python Setup & Packages Installation
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - name: Install Python Requirements
        run: |
          pip install -r requirements.txt

      - name: Jupyter Notebook execution
        id: jupyter
        run: jupyter execute text.ipynb
        shell: bash
